spring.application.name=account-service
server.port=8081

# MongoDB Atlas Cloud Connection (Primary Keys)
spring.data.mongodb.uri=mongodb+srv://shanugajayakody4_db_user:nZnnlJJitPjxxD3n@cluster0.zoid68x.mongodb.net/ridelink_account_db?retryWrites=true&w=majority&appName=Cluster0
spring.mongodb.uri=mongodb+srv://shanugajayakody4_db_user:nZnnlJJitPjxxD3n@cluster0.zoid68x.mongodb.net/ridelink_account_db?retryWrites=true&w=majority&appName=Cluster0

# JSON Formatting
spring.jackson.serialization.indent-output=true

# Swagger Path
springdoc.swagger-ui.path=/swagger-ui.html

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
jwt.refresh-expiration=604800000
